application: motivational-texter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /text/motivate
  script: main.app
  login: admin

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

